### ISSUE TITLE
Phrase - missing setValue method

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#22]
Could you please add the above-mentioned? - also, just for the sake of clarity, is it correct to assume that a phrase-portion is comprised of more than one word, just like a polymorphic word? - if so, then what exactly does the value field hold as such - is it just a concatenation of the various words making up the phrase?

**Comment by AdeebNqo** [comment]
The most recent commit (54e0b907b6dd95ef65f6756cb1b9e135b2eb1108) has introduced a setValue() method.

The phrase can be made up of multiple words. However, since it may be cumbersome to explicitly specify the individual words, then the 'value' can be set instead. For instance, consider the phrase "Hello World". Each word can be specified individually and then they can be used to create a phrase. However, one can also set the value as "Hello World" directly.
