### ISSUE TITLE
Add getValue function for Slot class

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#25]
@AdeebNqo  Slot class has setValue method but no corresponding getValue method. Instead, there is a toString method that will always throw an error whenever the setValue method is used. Check the insertValue method and how the toString method is implemented for more details on the resulting error here.

**Comment by AdeebNqo** [comment]
Can you please post a screen of template and error message that you in relation to the toString() of the Slot

**Comment by einstein07** [comment]
![slot-error-message](https://user-images.githubusercontent.com/53013773/188831296-fcd377d0-6e57-48ab-a3c0-46b9684b2192.png)
@AdeebNqo

**Comment by AdeebNqo** [comment]
I am looking at the line number of the code that that is throwing the exception (107). I can only conclude that you're using an old version of the library. Can you try using the binaries from the latest release and check if you get the same issue

**Comment by einstein07** [comment]
@AdeebNqo the new release does indeed have a getValue method. However, we still get an error when we invoke the template toString method. The source of the error is the toString method in the Slot class, see below:
![slot-error-new-binarries](https://user-images.githubusercontent.com/53013773/188856628-f254acab-119f-439b-90b2-22ad81812bf6.png)

**Comment by AdeebNqo** [comment]
I see what the problem is. The issue is likely due to a confusion regarding what the 'value' property is in the context of a slot.

Consider the following template: Hello [Name]

Suppose the first item is a polymorphic word and the second item is a slot. You have to create the elements in the following ways:

UnimorphicWord helloWord = new UnimorphicWord("Hello")
Slot nameSlot = new Slot("Name", null)

If you are inserting a value into the slot then you have to use insertValue --- you're not supposed to be using setValue. I am going to  mark setValue as deprecated so avoid problems.
