### ISSUE TITLE
Concord-type field

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#29]
It appears the type of a concord is determined from its feature list - however, there is no way of updating said features of a concord. Is this supposed to imply that the feature list of a concord should always be specified when the said word part is being constructed? - if so, then one should not be allowed to pass an empty feature list to the constructor, otherwise, there should be a way to insert/update the feature list, no?

**Comment by AdeebNqo** [comment]
Great observation. The initial design was focused on cases where you create a slot for which you know all of its features.

I have since updated the `Concord` class such that you can add/remove new classes. Here are the new methods that you can use to add or remove features to a concord class:

- `addFeature`
- `addFeatures`
- `removeFeature`
- `removeFeatures`
